### PR TITLE
ensure prompted password is passed to winrm session

### PR DESCRIPTION
**Pull request by mwrock**
There is currently a bug in v1.0 that does not pass the prompted password to the winrm session.

### CODE REVIEW

**Comment by adamedx** [comment]
@mwrock, curious about the cause -- was this introduced when we refactored a few things?

**Comment by adamedx** [comment]
Glad to see we added a test to catch this.

**Comment by mwrock** [comment]
yeah @adamedx  it got lost in the shuffle of option resolving refactoring

**Comment by adamedx** [comment]
:+1:

**Comment by ksubrama** [comment]
:+1:

**Pull request merged**
