### PR TITLE
run bundle install 3 times

### PR DESCRIPTION
**Pull request by btm**
this probably fixes appveyor in master by caching gems? It went green at least.

@jdmundrawala? /cc @ksubrama @smurawski

### CODE REVIEW

**Comment by btm** [comment]
This is an example of the failure. It happened multiple times at multiple points in the bundle install: https://ci.appveyor.com/project/Chef/knife-windows/branch/master/job/ww1pjyt4h4eyhvgh

**Comment by jdmundrawala** [comment]
it's probably better the bundle vendor or whatever bundler's way of doing that is, and cache that. But i'm not quite sure I understand why this fixes things

**Comment by btm** [comment]
@jdmundrawala I added the bundle install x3 pattern from core too. It passed again. Please hit merge if you think this is right.

**Comment by jdmundrawala** [comment]
you should get rid of the caching if it's not needed anymore

**Comment by btm** [comment]
it's hard to tell. appveyor smells funny today.

**Pull request merged**
