### PR TITLE
fixes #295 adding bootstrap support for policy

### LINKED ISSUE #295: Bootstrap missing policy_group, policy_name feature from Chef Client 12.5
The `knife bootstrap windows` subcommand is missing the new `policy_name` and policy_group` features introduced in Chef Client 12.5.

These features must be added to `knife-windows` for parity with core Chef.

See this test failure, which will be changed to ignore the failure (Chef Client 12.5 is not technically released).

``` 1) Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm contains the option flags
     Failure/Error: expect(filtered_keys).to match_array(bootstrap.options.keys - ref_ignore)
       expected collection contained:  [:bootstrap_install_command, :bootstrap_no_proxy, :bootstrap_proxy, :bootstrap_template, :bootstrap_url, :bootstrap_vault_file, :bootstrap_vault_item, :bootstrap_vault_json, :bootstrap_version, :chef_node_name, :distro, :first_boot_attributes, :hint, :host_key_verify, :identity_file, :node_ssl_verify_mode, :node_verify_api_cert, :policy_group, :policy_name, :prerelease, :run_list, :secret, :secret_file, :ssh_password, :ssh_port, :ssh_user, :tags, :template_file]
       actual collection contained:    [:bootstrap_install_command, :bootstrap_no_proxy, :bootstrap_proxy, :bootstrap_template, :bootstrap_url, :bootstrap_vault_file, :bootstrap_vault_item, :bootstrap_vault_json, :bootstrap_version, :chef_node_name, :distro, :first_boot_attributes, :hint, :host_key_verify, :identity_file, :node_ssl_verify_mode, :node_verify_api_cert, :prerelease, :run_list, :secret, :secret_file, :ssh_password, :ssh_port, :ssh_user, :tags, :template_file]
       the missing elements were:      [:policy_group, :policy_name]```

### PR DESCRIPTION
**Pull request by mwrock**
Fixes #295

### CODE REVIEW

**Comment by adamedx** [comment]
@danielsdeleo, can you take a look?

**Comment by danielsdeleo** [comment]
Looks like this should work. Has anyone run this just to be sure? :+1: from me though.

**Comment by btm** [comment]
@mwrock what was the order of changes in regard to validate_options? Did you rename validation_options to validate_winrm_options so we wouldn't override an higher validate_options method in Chef, and then need to stub it in some tests?

**Comment by danielsdeleo** [comment]
@btm yup. See: https://github.com/chef/chef/pull/3958

**Comment by mwrock** [comment]
I did create a policy on my hosted chef org and bootstrap a local windows node with these changes with much success.

**Comment by danielsdeleo** [comment]
:tada:

**Comment by btm** [comment]
:+1: :shipit:

**Pull request merged**
