### PR TITLE
Add validation for FQDN value

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Fix for issue https://github.com/chef/knife-windows/issues/378

### CODE REVIEW

**Comment by mwrock** [comment]
We shouldprobably just call `validate_name_args!` in the `run`  methods of both winrm and ssh commands.

**Comment by dheerajd-msys** [comment]
Hi @mwrock 
sure, have updated my code to use `validate_name_args!` and added specs accordingly

**Comment by mwrock** [comment]
Nice. Now `validate_name_args!` can be removed from https://github.com/chef/knife-windows/blob/710bceb8c7c17cdde8f6f59591add920ce1d9d33/lib/chef/knife/bootstrap_windows_base.rb#L294

**Comment by dheerajd-msys** [comment]
@mwrock,
Done, thanks for your feedback

**Comment by mwrock** [comment]
:+1:  great. Tested locally with no host and got the expected actionable error.

**Pull request merged**
