### PR TITLE
Make debugging of bootstrap easier

### PR DESCRIPTION
**Pull request by pburkholder**
See also https://github.com/chef/chef/pull/3662

### CODE REVIEW

**Comment by mcquin** [comment]
LGTM

@chef/client-maintainers (Sorry, I can't tag Windows-only maintainers.)

**Comment by tyler-ball** [comment]
:+1:

**Comment by jaym** [comment]
Does this contain passwords in it?

**Comment by ksubrama** [comment]
Hmm...  hadn't thought of that.  It does contain the client.pem and the config sections which may contain databag secrets.  Maybe we shouldn't do this...

**Comment by ksubrama** [comment]
Yep - it does contain secrets.  I'm reverting this.

**Pull request merged**
