### PR TITLE
Bumps winrm-s and winrm dependencies to address a winrm-s incompatibi…

### PR DESCRIPTION
**Pull request by mwrock**
…lity bug with winrm 1.5

### CODE REVIEW

**Comment by danielsdeleo** [comment]
LGTM, though make sure to click rebuild on appveyor after you release winrm-s

**Comment by ksubrama** [comment]
:+1:

**Comment by mwrock** [comment]
The appveyor failure here is very weird. Need to investigate but its unrelated to this change so I'm gonna go ahead and ship.

**Comment by mwrock** [comment]
I'm rebuilding appveyor master first to see if that fails too just to appease paranoia

**Pull request merged**
