### PR TITLE
Adding a proxy env var to wget.ps1

### PR DESCRIPTION
**Pull request by tristanmorgan**
Hi, I'm trying to get a machine to bootstrap from behind a proxy with knife[:bootstrap_proxy] set in my knife.rb and the powershell script didn't pick up the environment vars.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @tristanmorgan

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by mwrock** [comment]
Setting the proxy on the webclient here makes total sense. It just seems odd to me that this has never come up with other proxy bound users. Any background @btm @adamedx @ksubrama on this or have we just been "lucky"?

**Comment by mwrock** [comment]
I'm :+1:  here and i think the build failures are due to problems elsewhere which I'll investigate.

**Comment by tristanmorgan** [comment]
I'll rebase after the RVM branch has been merged to test the build failures.

**Comment by mwrock** [comment]
@tristanmorgan go ahead and rebase this on top of master now that #366 is merged.

**Comment by mwrock** [comment]
cc @chef/client-windows

**Comment by ksubrama** [comment]
:+1:

**Pull request merged**
