### PR TITLE
Adds support for server 2016

### PR DESCRIPTION
**Pull request by spuder**
Resolves issue #441 

I am not sure how to add tests for this, guidance appreciated.

### CODE REVIEW

**Comment by spuder** [comment]
Competes with https://github.com/chef/knife-windows/pull/433/files

**Comment by joncloud** [comment]
Would lines [this](https://github.com/chef/knife-windows/pull/442/files#diff-6594420d1edc8fb2383cce0d238968b4R53) need to be updated too?

```batch
@set LATEST_OS_VERSION_MAJOR=6
@set LATEST_OS_VERSION_MINOR=3
```

**Comment by spuder** [comment]
Not sure, possibly. Depends what the default OS should be.

**Comment by spuder** [comment]
I'm closing this merge request in favor of https://github.com/chef/knife-windows/pull/433

**Pull request closed without merging**
