### PR TITLE
Removed deprecated host_key_verification, distro and template_file options

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>

## Descriptions

- Removed deprecated `--host-key-verification`, `--distro` & `--template-file` option.
- `--host-key-verify` is used now instead of `--host-key-verification`
- `--bootstrap-template-file` is used now instead of  `--distro` & `--template-file`

## Resolved Issue
Fixes https://github.com/chef/knife-windows/issues/469

### CODE REVIEW

**Comment by tas50** [comment]
Agree with @rhass here. Let's make sure we nuke every mention of this old option including our tests.

**Comment by dheerajd-msys** [comment]
Thanks @tas50 and @rhass I will do that.

**Comment by dheerajd-msys** [comment]
We may need to update travis and appveyor to get all this green. Travis and AppVeyor is failing for `Environment: ruby_version=24, chef_version=~>13.0`. 

@rhass & @tas50 Could you please take a look?

**Comment by Vasu1105** [comment]
@dheerajd-msys : We should remove --template-file and --distro option also in this same PR.

**Comment by tas50** [comment]
@dheerajd-msys looks like travis is failing on this spec that's still using the distro flag: https://github.com/chef/knife-windows/blob/master/spec/unit/knife/bootstrap_windows_winrm_spec.rb#L48

**Comment by tas50** [comment]
As part of this PR you can remove Chef 13 testing since we'll require Chef 14 or later. We probably want to note that in the readme. You can also change the minimum required ruby version to 2.4 in the gemspec since that's the same as what Chef 14 required.

**Comment by dheerajd-msys** [comment]
@tas50 Problem here is that even if we remove `chef v13` and use `chef v14` it will still not make travis happy. Because `--identity-file` option is not removed yet from `chef v14` as you can see here https://github.com/chef/chef/blob/v14.9.13/lib/chef/knife/bootstrap.rb#L81.

**Comment by tas50** [comment]
We will probably need to keep identity_file for now then.

**Pull request merged**
