### PR TITLE
Add fips flag to boostrap

### PR DESCRIPTION
**Pull request by jaym**
This is required to make the tests pass for chef-client
changes

### CODE REVIEW

**Comment by mwrock** [comment]
:+1: pending greenness

**Comment by mwrock** [comment]
PS. i just submitted https://github.com/chef/chef/pull/4459 to fix some of this but I think you have more probs than just that here :)

**Comment by jaym** [comment]
yea, the tests here require chef to be merged. The tests in my pr in chef require this to be merged. I blame @btm for not allowing us to break knife-windows all the time

**Comment by jaym** [comment]
merging with red, https://github.com/chef/chef/pull/4287 will fix them

**Pull request merged**
